### PR TITLE
Refuse to delete locations in use by a course-listing or a course-reserve

### PR DESCRIPTION
**Pull request by MikeTaylor**
Fixes UITEN-74.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
OK, second try. I am interested in reviews from:
* @NikitaSedyx who just did the big rearrangement and is generally working on this module.
* @zburke whose code (albeit now transplanted) I have modified here.
* @VictorSoroka1 who made the most recent release.

**Comment by NikitaSedyx** [comment]
I've raised a question in the ticket so please don't merge this one for now

+ you use okapi interfaces from other modules, and they are not described in package.json, I see you covered them by `hasInterface`, but I'm not sure it's right way, so let's discuss with POs

**Comment by MikeTaylor** [comment]
We don't need PO involvement in a technical fix. We certainly can consult POs for opinions on how this approach might be generalised to other modules whose use of locations does not currently prevent their deletion, but that is no reason to prevent Course Reserves from doing the right thing.

Inspecting interfaces from other modules is the very reason interface provisions are published: see similar code in
* ui-licences: https://github.com/folio-org/ui-licenses/blob/master/src/routes/EditLicenseRoute.js#L62
* ui-agreements: https://github.com/folio-org/ui-agreements/blob/master/src/routes/AgreementViewRoute.js#L70
* ui-users: https://github.com/folio-org/ui-users/blob/master/src/views/UserDetail/UserDetail.js#L513

**Comment by VictorSoroka1** [comment]
@zburke, I don't see such an option in the [docs](https://github.com/folio-org/stripes/blob/master/doc/dev-guide.md#modules). Could you please describe its purpose?

**Comment by MikeTaylor** [comment]
That's weird, I thought I did the documentation for `optionalOkapiInterfaces` when I added the code. I guess not. I'll go back and add it.

**Comment by MikeTaylor** [comment]
Yep, you're right, I didn't do the doc: see https://github.com/folio-org/stripes-core/commit/358342c2c2e63bcceaeae5b8c5b68a850d2afdcd

Stand by ...

**Comment by MikeTaylor** [comment]
Here you go: https://github.com/folio-org/stripes/blob/master/doc/dev-guide.md#the-package-file-stripes-entry

> * `optionalOkapiInterfaces` -- an optional object specifying back-end modules that Okapi _may_ provide, and whose presence the current module responds to, but whose absence does not impede the current module's functioning: for example, the Users app may declare an optional interface for `circulation`, and its UI may provide information about users' loans when that interface is present. The format is the same as that of `okapiInterfaces`.

**Comment by VictorSoroka1** [comment]
@MikeTaylor, thank you. That was quick.

**Comment by MikeTaylor** [comment]
I aim to please :-) Especially when the issue is down to something I myself overlooked.

**Comment by MikeTaylor** [comment]
Added `optionalOkapiInterfaces` to the `ui-tenant-settings` package file.

**Comment by MikeTaylor** [comment]
All right — with two review approvals, I am going to go ahead and merge this solution to the problem of data consistence with Course Reserves. The wider problem of data consistency remains a real and important one, which POs certainly should feel free to discuss.

**Pull request merged**
