### PR TITLE
UICIRC-281: Delete unnecessary asterisks.

### PR DESCRIPTION
**Pull request by OleksandrAntonenko1**
# Description 
Go to Settings > Tenant > Service points > Create/Edit Location

If a required field label displays a double asterisk then update translation file
If a required field label displays text-color asterisk then update translation file and use the `required` prop for that field.

# Screenshots
Before | After
------------ | -------------
Screen Shot 2019-07-18 at 2 21 49 PM|Screen Shot 2019-07-18 at 2 59 46 PM

### CODE REVIEW

**Comment by OleksandrAntonenko1** [comment]
> A simpler implementation allows stripes-components to handle most of this work:
> 
> 1. remove the asterisks from field-names in `translations/ui-tenant-settings/en.json` (translators will see the change and propagate the change to en-US.json, ar.json, etc.)
> 2. pass the prop `required` to required fields (stripes-components will take of formatting the asterisk and placing it near the label as appropriate depending on the field-type)

There is a problem with the required prop. Cause it triggers browser validation. It's shown on the gifs.
With Required property:
chrome-capture 3 44 41 PM
Without:
chrome-capture copy 3 44 41 PM

**Comment by zburke** [comment]
I don't follow. Isn't browser validation the right thing?

**Comment by OleksandrAntonenko1** [comment]
I have talked with Khalilah and she approved that in this case, we don't need browser validation cause we have another type of it. Also, browser validation is not consistent with the project practices.

**Comment by zburke** [comment]
Is there a ticket you can point me to that discusses this other approach to validation? This is news to me.

**Pull request merged**
